spring:
  # 파일 사이즈 지정
  servlet:
    multipart:
      maxFileSize: 10MB
      maxRequestSize: 100MB

  h2:
    console:
      enabled: true
      path: /h2

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:test
    username: sa
    password:

  flyway:
    enabled: true
    baselineOnMigrate: true
    locations: classpath:db/migration/{vendor},classpath:db/seed/local # when you want to give test seed, add location test seed too

  jpa:
    show-sql: true
    generate-ddl: false
    hibernate:
      ddl-auto: validate

    properties:
      hibernate:
        format_sql: true

  kafka:
    bootstrap-servers: 13.209.250.13:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      auto-offset-reset: earliest
      enable-auto-commit: true

app:
  topic:
    raw:
      raw-data-upload: raw-data-upload
  web-client:
    base-url: http://a42e30416f79f4cbc9bb75a1a0e132ed-738c4e9a914338da.elb.ap-northeast-2.amazonaws.com

## aws S3 관련 정보
cloud:
  aws:
    s3:
      bucket: belloga-dev-s3-raw-data-bucket
      unzip-bucket: belloga-dev-s3-unzip-bucket
      dir: local
    region:
      static: ap-northeast-2
    stack:
      auto: false
    credentials:
      instanceProfile: true
