apiVersion: v1
kind: Service
metadata:
  name: raw-data-service
  labels:
    app: raw-data-service
    service: raw-data-service
spec:
  ports:
    - port: 8080
      name: http
  selector:
    app: raw-data-service
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: belloga-raw-data-service
  labels:
    account: raw-data-service
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: raw-data-service-v1
  labels:
    app: raw-data-service
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: raw-data-service
      version: v1
  template:
    metadata:
      labels:
        app: raw-data-service
        version: v1
    spec:
      serviceAccountName: belloga-raw-data-service
      containers:
        - name: raw-data-service
          image: 023778162658.dkr.ecr.ap-northeast-2.amazonaws.com/belloga-raw-data-service:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: local
